{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLogFileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/client_sdk\/lsclientlogfilemanager\/newlogfilename"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/client_sdk\/lsclientlogfilemanager\/newlogfilename"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/newLogFileName","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLogFileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"newLogFileName","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@client_sdk@objc(cs)LSClientLogFileManager(py)newLogFileName","modules":[{"name":"client_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"newLogFileName"}]},"hierarchy":{"paths":[["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager"]]},"references":{"doc://com.ricoh.livestreaming/documentation/client_sdk/LSClientLogFileManager":{"role":"symbol","title":"LSClientLogFileManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSClientLogFileManager"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSClientLogFileManager"}],"url":"\/documentation\/client_sdk\/lsclientlogfilemanager"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSClientLogFileManager/newLogFileName":{"role":"symbol","title":"newLogFileName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLogFileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/newLogFileName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"newLogFileName"}],"url":"\/documentation\/client_sdk\/lsclientlogfilemanager\/newlogfilename"},"doc://com.ricoh.livestreaming/documentation/client_sdk":{"role":"collection","title":"client_sdk","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"newLogFileName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"newLogFileName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"newLogFileName"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager\/title","value":"LSClientLogFileManager"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager\/fragments","value":[{"kind":"identifier","text":"LSClientLogFileManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager~1newLogFileName\/title","value":"newLogFileName"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager~1newLogFileName\/fragments","value":[{"kind":"identifier","text":"newLogFileName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}