{"variants":[{"paths":["\/documentation\/client_sdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/client_sdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Camera2VideoCapturer","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ClientLogOption","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ErrorDetail","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSAddLocalTrackEvent","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSAddRemoteConnectionEvent","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSAddRemoteTrackEvent","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSOpenEvent","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSRemoveRemoteConnectionEvent","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSTrack","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSTrackOption","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LibWebrtcLogOption","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/MediaStreamConstraints","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Option","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/PixelBufferCapturer","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ReceivingOption","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SDKError","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SDKErrorEvent","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SendingOption","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SendingVideoOption"]},{"title":"Protocols","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ClientDelegate","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/VideoCapturer"]},{"title":"Enumerations","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ClientLogLevel","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ErrorType","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/IceServersProtocol","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LibWebRTCLogLevel","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/MuteType","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SendingPriority","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/State","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/VideoCodecType","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/VideoOptionMuteType","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/VideoRequirement"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"client_sdk","title":"client_sdk","symbolKind":"module","role":"collection","modules":[{"name":"client_sdk"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.ricoh.livestreaming/documentation/client_sdk/Client":{"role":"symbol","title":"Client","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Client"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Client"}],"url":"\/documentation\/client_sdk\/client"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSOpenEvent":{"role":"symbol","title":"LSOpenEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSOpenEvent"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSOpenEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSOpenEvent"}],"url":"\/documentation\/client_sdk\/lsopenevent"},"doc://com.ricoh.livestreaming/documentation/client_sdk/VideoCapturer":{"role":"symbol","title":"VideoCapturer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoCapturer"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/VideoCapturer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoCapturer"}],"url":"\/documentation\/client_sdk\/videocapturer"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LibWebRTCLogLevel":{"role":"symbol","title":"LibWebRTCLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LibWebRTCLogLevel"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LibWebRTCLogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LibWebRTCLogLevel"}],"url":"\/documentation\/client_sdk\/libwebrtcloglevel"},"doc://com.ricoh.livestreaming/documentation/client_sdk/ClientLogLevel":{"role":"symbol","title":"ClientLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientLogLevel"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ClientLogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientLogLevel"}],"url":"\/documentation\/client_sdk\/clientloglevel"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSAddLocalTrackEvent":{"role":"symbol","title":"LSAddLocalTrackEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSAddLocalTrackEvent"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSAddLocalTrackEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSAddLocalTrackEvent"}],"url":"\/documentation\/client_sdk\/lsaddlocaltrackevent"},"doc://com.ricoh.livestreaming/documentation/client_sdk/SDKError":{"role":"symbol","title":"SDKError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKError"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SDKError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKError"}],"url":"\/documentation\/client_sdk\/sdkerror"},"doc://com.ricoh.livestreaming/documentation/client_sdk/SendingVideoOption":{"role":"symbol","title":"SendingVideoOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendingVideoOption"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SendingVideoOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendingVideoOption"}],"url":"\/documentation\/client_sdk\/sendingvideooption"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSRemoveRemoteConnectionEvent":{"role":"symbol","title":"LSRemoveRemoteConnectionEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSRemoveRemoteConnectionEvent"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSRemoveRemoteConnectionEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSRemoveRemoteConnectionEvent"}],"url":"\/documentation\/client_sdk\/lsremoveremoteconnectionevent"},"doc://com.ricoh.livestreaming/documentation/client_sdk/State":{"role":"symbol","title":"State","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/State","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"State"}],"url":"\/documentation\/client_sdk\/state"},"doc://com.ricoh.livestreaming/documentation/client_sdk/IceServersProtocol":{"role":"symbol","title":"IceServersProtocol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IceServersProtocol"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/IceServersProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IceServersProtocol"}],"url":"\/documentation\/client_sdk\/iceserversprotocol"},"doc://com.ricoh.livestreaming/documentation/client_sdk/SendingOption":{"role":"symbol","title":"SendingOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendingOption"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SendingOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendingOption"}],"url":"\/documentation\/client_sdk\/sendingoption"},"doc://com.ricoh.livestreaming/documentation/client_sdk/SendingPriority":{"role":"symbol","title":"SendingPriority","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SendingPriority"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SendingPriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SendingPriority"}],"url":"\/documentation\/client_sdk\/sendingpriority"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Camera2VideoCapturer":{"role":"symbol","title":"Camera2VideoCapturer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Camera2VideoCapturer"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Camera2VideoCapturer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Camera2VideoCapturer"}],"url":"\/documentation\/client_sdk\/camera2videocapturer"},"doc://com.ricoh.livestreaming/documentation/client_sdk/VideoRequirement":{"role":"symbol","title":"VideoRequirement","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoRequirement"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/VideoRequirement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoRequirement"}],"url":"\/documentation\/client_sdk\/videorequirement"},"doc://com.ricoh.livestreaming/documentation/client_sdk/MediaStreamConstraints":{"role":"symbol","title":"MediaStreamConstraints","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaStreamConstraints"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/MediaStreamConstraints","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MediaStreamConstraints"}],"url":"\/documentation\/client_sdk\/mediastreamconstraints"},"doc://com.ricoh.livestreaming/documentation/client_sdk/ClientDelegate":{"role":"symbol","title":"ClientDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientDelegate"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ClientDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientDelegate"}],"url":"\/documentation\/client_sdk\/clientdelegate"},"doc://com.ricoh.livestreaming/documentation/client_sdk/ReceivingOption":{"role":"symbol","title":"ReceivingOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReceivingOption"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ReceivingOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReceivingOption"}],"url":"\/documentation\/client_sdk\/receivingoption"},"doc://com.ricoh.livestreaming/documentation/client_sdk/ErrorDetail":{"role":"symbol","title":"ErrorDetail","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorDetail"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ErrorDetail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorDetail"}],"url":"\/documentation\/client_sdk\/errordetail"},"doc://com.ricoh.livestreaming/documentation/client_sdk/SDKErrorEvent":{"role":"symbol","title":"SDKErrorEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKErrorEvent"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/SDKErrorEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKErrorEvent"}],"url":"\/documentation\/client_sdk\/sdkerrorevent"},"doc://com.ricoh.livestreaming/documentation/client_sdk":{"role":"collection","title":"client_sdk","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Option":{"role":"symbol","title":"Option","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Option"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Option","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Option"}],"url":"\/documentation\/client_sdk\/option"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSTrackOption":{"role":"symbol","title":"LSTrackOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSTrackOption"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSTrackOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSTrackOption"}],"url":"\/documentation\/client_sdk\/lstrackoption"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSAddRemoteConnectionEvent":{"role":"symbol","title":"LSAddRemoteConnectionEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSAddRemoteConnectionEvent"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSAddRemoteConnectionEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSAddRemoteConnectionEvent"}],"url":"\/documentation\/client_sdk\/lsaddremoteconnectionevent"},"doc://com.ricoh.livestreaming/documentation/client_sdk/client_sdkVersionNumber":{"role":"symbol","title":"client_sdkVersionNumber","fragments":[{"kind":"identifier","text":"client_sdkVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for client_sdk."}],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/client_sdkVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client_sdkversionnumber"},"doc://com.ricoh.livestreaming/documentation/client_sdk/ErrorType":{"role":"symbol","title":"ErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorType"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorType"}],"url":"\/documentation\/client_sdk\/errortype"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSAddRemoteTrackEvent":{"role":"symbol","title":"LSAddRemoteTrackEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSAddRemoteTrackEvent"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSAddRemoteTrackEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSAddRemoteTrackEvent"}],"url":"\/documentation\/client_sdk\/lsaddremotetrackevent"},"doc://com.ricoh.livestreaming/documentation/client_sdk/VideoOptionMuteType":{"role":"symbol","title":"VideoOptionMuteType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoOptionMuteType"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/VideoOptionMuteType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoOptionMuteType"}],"url":"\/documentation\/client_sdk\/videooptionmutetype"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSTrack":{"role":"symbol","title":"LSTrack","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSTrack"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSTrack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSTrack"}],"url":"\/documentation\/client_sdk\/lstrack"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LibWebrtcLogOption":{"role":"symbol","title":"LibWebrtcLogOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LibWebrtcLogOption"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LibWebrtcLogOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LibWebrtcLogOption"}],"url":"\/documentation\/client_sdk\/libwebrtclogoption"},"doc://com.ricoh.livestreaming/documentation/client_sdk/PixelBufferCapturer":{"role":"symbol","title":"PixelBufferCapturer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PixelBufferCapturer"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/PixelBufferCapturer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PixelBufferCapturer"}],"url":"\/documentation\/client_sdk\/pixelbuffercapturer"},"doc://com.ricoh.livestreaming/documentation/client_sdk/VideoCodecType":{"role":"symbol","title":"VideoCodecType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoCodecType"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/VideoCodecType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoCodecType"}],"url":"\/documentation\/client_sdk\/videocodectype"},"doc://com.ricoh.livestreaming/documentation/client_sdk/client_sdkVersionString":{"role":"symbol","title":"client_sdkVersionString","fragments":[{"kind":"identifier","text":"client_sdkVersionString"}],"abstract":[{"type":"text","text":"Project version string for client_sdk."}],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/client_sdkVersionString","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client_sdkversionstring"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSClientLogFileManager":{"role":"symbol","title":"LSClientLogFileManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSClientLogFileManager"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSClientLogFileManager"}],"url":"\/documentation\/client_sdk\/lsclientlogfilemanager"},"doc://com.ricoh.livestreaming/documentation/client_sdk/ClientLogOption":{"role":"symbol","title":"ClientLogOption","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientLogOption"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/ClientLogOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientLogOption"}],"url":"\/documentation\/client_sdk\/clientlogoption"},"doc://com.ricoh.livestreaming/documentation/client_sdk/MuteType":{"role":"symbol","title":"MuteType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MuteType"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/MuteType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MuteType"}],"url":"\/documentation\/client_sdk\/mutetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager"]},{"title":"Variables","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/client_sdkVersionNumber","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/client_sdkVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/title","value":"Client"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/fragments","value":[{"kind":"identifier","text":"Client"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager\/title","value":"LSClientLogFileManager"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager\/fragments","value":[{"kind":"identifier","text":"LSClientLogFileManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}