{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Client"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/client_sdk\/client"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/client_sdk\/client"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ricoh.livestreaming\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.ricoh.livestreaming\/objc(pl)NSObject","doc:\/\/com.ricoh.livestreaming\/s7CVarArgP","doc:\/\/com.ricoh.livestreaming\/s28CustomDebugStringConvertibleP","doc:\/\/com.ricoh.livestreaming\/s23CustomStringConvertibleP","doc:\/\/com.ricoh.livestreaming\/SQ","doc:\/\/com.ricoh.livestreaming\/SH","doc:\/\/com.ricoh.livestreaming\/objc(pl)RTCPeerConnectionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/init()","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/init(clientLogOption:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/changeMediaRequirements(connectionId:videoRequirement:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/changeMute(lsTrack:nextMuteType:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/changeVideoSendBitrate(maxBitrateKbps:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/changeVideoSendFramerate(maxFramerate:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/connect(clientId:accessToken:option:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/disconnect()","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/getState()","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/getStats(mediaStreamTrack:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/getUserMedia(constraints:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/replaceMediaStreamTrack(lsTrack:mediaStream:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/setLibWebrtcLogOption(option:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/updateMeta(meta:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/updateTrackMeta(lsTrack:meta:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Client"}],"title":"Client","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@client_sdk@objc(cs)Client","modules":[{"name":"client_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"Client"}]},"hierarchy":{"paths":[["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk"]]},"references":{"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/connect(clientId:accessToken:option:)":{"role":"symbol","title":"connect(clientId:accessToken:option:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Option","preciseIdentifier":"s:10client_sdk6OptionC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/connect(clientId:accessToken:option:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/connect(clientid:accesstoken:option:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/client_sdk\/client\/init()"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client":{"role":"symbol","title":"Client","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Client"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Client"}],"url":"\/documentation\/client_sdk\/client"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/getUserMedia(constraints:)":{"role":"symbol","title":"getUserMedia(constraints:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserMedia"},{"kind":"text","text":"("},{"kind":"externalParam","text":"constraints"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MediaStreamConstraints","preciseIdentifier":"s:10client_sdk22MediaStreamConstraintsC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"RTCMediaStream","preciseIdentifier":"c:objc(cs)RTCMediaStream"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/getUserMedia(constraints:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/getusermedia(constraints:)"},"doc://com.ricoh.livestreaming/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.ricoh.livestreaming\/objc(pl)NSObject"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/disconnect()":{"role":"symbol","title":"disconnect()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnect"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/disconnect()","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/disconnect()"},"doc://com.ricoh.livestreaming/objc(pl)RTCPeerConnectionDelegate":{"type":"unresolvable","title":"RTCPeerConnectionDelegate","identifier":"doc:\/\/com.ricoh.livestreaming\/objc(pl)RTCPeerConnectionDelegate"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/changeVideoSendFramerate(maxFramerate:)":{"role":"symbol","title":"changeVideoSendFramerate(maxFramerate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeVideoSendFramerate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxFramerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/changeVideoSendFramerate(maxFramerate:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/changevideosendframerate(maxframerate:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/updateMeta(meta:)":{"role":"symbol","title":"updateMeta(meta:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateMeta"},{"kind":"text","text":"("},{"kind":"externalParam","text":"meta"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"kind":"text","text":">) "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/updateMeta(meta:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/updatemeta(meta:)"},"doc://com.ricoh.livestreaming/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.ricoh.livestreaming\/s7CVarArgP"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/updateTrackMeta(lsTrack:meta:)":{"role":"symbol","title":"updateTrackMeta(lsTrack:meta:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTrackMeta"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lsTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LSTrack","preciseIdentifier":"s:10client_sdk7LSTrackC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"meta"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"kind":"text","text":">) "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/updateTrackMeta(lsTrack:meta:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/updatetrackmeta(lstrack:meta:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/getStats(mediaStreamTrack:)":{"role":"symbol","title":"getStats(mediaStreamTrack:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStats"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mediaStreamTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCMediaStreamTrack","preciseIdentifier":"c:objc(cs)RTCMediaStreamTrack"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"RTCStatisticsReport","preciseIdentifier":"c:objc(cs)RTCStatisticsReport"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/getStats(mediaStreamTrack:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/getstats(mediastreamtrack:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/init(clientLogOption:)":{"role":"symbol","title":"init(clientLogOption:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientLogOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClientLogOption","preciseIdentifier":"s:10client_sdk15ClientLogOptionC"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/init(clientLogOption:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/init(clientlogoption:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk":{"role":"collection","title":"client_sdk","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk"},"doc://com.ricoh.livestreaming/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ricoh.livestreaming\/SQ"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/getState()":{"role":"symbol","title":"getState()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getState"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"s:10client_sdk5StateO"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/getState()","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/getstate()"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/changeVideoSendBitrate(maxBitrateKbps:)":{"role":"symbol","title":"changeVideoSendBitrate(maxBitrateKbps:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeVideoSendBitrate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxBitrateKbps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/changeVideoSendBitrate(maxBitrateKbps:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/changevideosendbitrate(maxbitratekbps:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/changeMediaRequirements(connectionId:videoRequirement:)":{"role":"symbol","title":"changeMediaRequirements(connectionId:videoRequirement:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeMediaRequirements"},{"kind":"text","text":"("},{"kind":"externalParam","text":"connectionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoRequirement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoRequirement","preciseIdentifier":"s:10client_sdk16VideoRequirementO"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/changeMediaRequirements(connectionId:videoRequirement:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/changemediarequirements(connectionid:videorequirement:)"},"doc://com.ricoh.livestreaming/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.ricoh.livestreaming\/objc(cs)NSObject"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/setLibWebrtcLogOption(option:)":{"role":"symbol","title":"setLibWebrtcLogOption(option:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLibWebrtcLogOption"},{"kind":"text","text":"("},{"kind":"externalParam","text":"option"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LibWebrtcLogOption","preciseIdentifier":"s:10client_sdk18LibWebrtcLogOptionC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/setLibWebrtcLogOption(option:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/setlibwebrtclogoption(option:)"},"doc://com.ricoh.livestreaming/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.ricoh.livestreaming\/s23CustomStringConvertibleP"},"doc://com.ricoh.livestreaming/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.ricoh.livestreaming\/SH"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/RTCPeerConnectionDelegate-Implementations":{"role":"collectionGroup","title":"RTCPeerConnectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/client_sdk\/client\/rtcpeerconnectiondelegate-implementations"},"doc://com.ricoh.livestreaming/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.ricoh.livestreaming\/s28CustomDebugStringConvertibleP"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/changeMute(lsTrack:nextMuteType:)":{"role":"symbol","title":"changeMute(lsTrack:nextMuteType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeMute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lsTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LSTrack","preciseIdentifier":"s:10client_sdk7LSTrackC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nextMuteType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MuteType","preciseIdentifier":"s:10client_sdk8MuteTypeO"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/changeMute(lsTrack:nextMuteType:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/changemute(lstrack:nextmutetype:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/replaceMediaStreamTrack(lsTrack:mediaStream:)":{"role":"symbol","title":"replaceMediaStreamTrack(lsTrack:mediaStream:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceMediaStreamTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lsTrack"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LSTrack","preciseIdentifier":"s:10client_sdk7LSTrackC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaStream"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCMediaStreamTrack","preciseIdentifier":"c:objc(cs)RTCMediaStreamTrack"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/replaceMediaStreamTrack(lsTrack:mediaStream:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/replacemediastreamtrack(lstrack:mediastream:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClientDelegate","preciseIdentifier":"s:10client_sdk14ClientDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/client\/delegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Client"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Client"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Client"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/init()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.ricoh.livestreaming\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.ricoh.livestreaming\/objc(pl)RTCPeerConnectionDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Client"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/title","value":"Client"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/fragments","value":[{"kind":"identifier","text":"Client"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}