{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSClientLogFileManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/client_sdk\/lsclientlogfilemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/client_sdk\/lsclientlogfilemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ricoh.livestreaming\/objc(cs)DDLogFileManagerDefault"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.ricoh.livestreaming\/objc(pl)DDLogFileManager","doc:\/\/com.ricoh.livestreaming\/objc(pl)NSObject","doc:\/\/com.ricoh.livestreaming\/s7CVarArgP","doc:\/\/com.ricoh.livestreaming\/s28CustomDebugStringConvertibleP","doc:\/\/com.ricoh.livestreaming\/s23CustomStringConvertibleP","doc:\/\/com.ricoh.livestreaming\/SQ","doc:\/\/com.ricoh.livestreaming\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/init(fileNamePrefix:logsDirectory:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/newLogFileName"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/isLogFile(withName:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSClientLogFileManager"}],"title":"LSClientLogFileManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@client_sdk@objc(cs)LSClientLogFileManager","modules":[{"name":"client_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"LSClientLogFileManager"}]},"hierarchy":{"paths":[["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk"]]},"references":{"doc://com.ricoh.livestreaming/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.ricoh.livestreaming\/objc(pl)NSObject"},"doc://com.ricoh.livestreaming/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.ricoh.livestreaming\/s28CustomDebugStringConvertibleP"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSClientLogFileManager/newLogFileName":{"role":"symbol","title":"newLogFileName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"newLogFileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/newLogFileName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"newLogFileName"}],"url":"\/documentation\/client_sdk\/lsclientlogfilemanager\/newlogfilename"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSClientLogFileManager/init(fileNamePrefix:logsDirectory:)":{"role":"symbol","title":"init(fileNamePrefix:logsDirectory:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileNamePrefix"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"logsDirectory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/init(fileNamePrefix:logsDirectory:)","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk\/lsclientlogfilemanager\/init(filenameprefix:logsdirectory:)"},"doc://com.ricoh.livestreaming/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.ricoh.livestreaming\/s23CustomStringConvertibleP"},"doc://com.ricoh.livestreaming/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.ricoh.livestreaming\/s7CVarArgP"},"doc://com.ricoh.livestreaming/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.ricoh.livestreaming\/SH"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSClientLogFileManager":{"role":"symbol","title":"LSClientLogFileManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSClientLogFileManager"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LSClientLogFileManager"}],"url":"\/documentation\/client_sdk\/lsclientlogfilemanager"},"doc://com.ricoh.livestreaming/objc(pl)DDLogFileManager":{"type":"unresolvable","title":"CocoaLumberjack.DDLogFileManager","identifier":"doc:\/\/com.ricoh.livestreaming\/objc(pl)DDLogFileManager"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSClientLogFileManager/initWithLogsDirectory:":{"role":"symbol","title":"initWithLogsDirectory:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLogsDirectory:"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/initWithLogsDirectory:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithLogsDirectory:"}],"url":"\/documentation\/client_sdk\/lsclientlogfilemanager\/initwithlogsdirectory:"},"doc://com.ricoh.livestreaming/documentation/client_sdk":{"role":"collection","title":"client_sdk","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk"},"doc://com.ricoh.livestreaming/objc(cs)DDLogFileManagerDefault":{"type":"unresolvable","title":"DDLogFileManagerDefault","identifier":"doc:\/\/com.ricoh.livestreaming\/objc(cs)DDLogFileManagerDefault"},"doc://com.ricoh.livestreaming/documentation/client_sdk/LSClientLogFileManager/isLogFile(withName:)":{"role":"symbol","title":"isLogFile(withName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLogFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/isLogFile(withName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isLogFile:"}],"url":"\/documentation\/client_sdk\/lsclientlogfilemanager\/islogfile(withname:)"},"doc://com.ricoh.livestreaming/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.ricoh.livestreaming\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"LSClientLogFileManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LSClientLogFileManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LSClientLogFileManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/newLogFileName"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/initWithLogsDirectory:","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/LSClientLogFileManager\/isLogFile(withName:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.ricoh.livestreaming\/objc(cs)DDLogFileManagerDefault"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LSClientLogFileManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"DDLogFileManagerDefault","preciseIdentifier":"c:objc(cs)DDLogFileManagerDefault"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager~1newLogFileName\/title","value":"newLogFileName"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager~1newLogFileName\/fragments","value":[{"kind":"identifier","text":"newLogFileName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager\/title","value":"LSClientLogFileManager"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager\/fragments","value":[{"kind":"identifier","text":"LSClientLogFileManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager~1isLogFile(withName:)\/title","value":"isLogFile:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1LSClientLogFileManager~1isLogFile(withName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLogFile:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}