{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"peerConnection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didGenerate"},{"kind":"text","text":" "},{"kind":"internalParam","text":"candidate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCIceCandidate","preciseIdentifier":"c:objc(cs)RTCIceCandidate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/client_sdk\/client\/peerconnection(_:didgenerate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/client_sdk\/client\/peerconnection(_:didgenerate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didGenerate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RTCPeerConnectionDelegate.peerConnection(_:didGenerate:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didGenerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCIceCandidate","preciseIdentifier":"c:objc(cs)RTCIceCandidate"},{"kind":"text","text":")"}],"title":"peerConnection(_:didGenerate:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@client_sdk@objc(cs)Client(im)peerConnection:didGenerateIceCandidate:","modules":[{"name":"client_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"peerConnection:didGenerateIceCandidate:"}]},"hierarchy":{"paths":[["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations"]]},"references":{"doc://com.ricoh.livestreaming/documentation/client_sdk":{"role":"collection","title":"client_sdk","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/RTCPeerConnectionDelegate-Implementations":{"role":"collectionGroup","title":"RTCPeerConnectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/client_sdk\/client\/rtcpeerconnectiondelegate-implementations"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didGenerate:)":{"role":"symbol","title":"peerConnection(_:didGenerate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didGenerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCIceCandidate","preciseIdentifier":"c:objc(cs)RTCIceCandidate"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didGenerate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didGenerateIceCandidate:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didgenerate:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client":{"role":"symbol","title":"Client","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Client"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Client"}],"url":"\/documentation\/client_sdk\/client"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"peerConnection:didGenerateIceCandidate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didGenerateIceCandidate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"peerConnection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peerConnection"},{"kind":"text","text":" "},{"kind":"identifier","text":"didGenerateIceCandidate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCIceCandidate","preciseIdentifier":"c:objc(cs)RTCIceCandidate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"candidate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didGenerate:)\/title","value":"peerConnection:didGenerateIceCandidate:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didGenerate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didGenerateIceCandidate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/title","value":"Client"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/fragments","value":[{"kind":"identifier","text":"Client"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}