{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"peerConnection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCIceConnectionState","preciseIdentifier":"c:@E@RTCIceConnectionState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/client_sdk\/client\/peerconnection(_:didchange:)-1m295"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/client_sdk\/client\/peerconnection(_:didchange:)-1m295"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-1m295","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RTCPeerConnectionDelegate.peerConnection(_:didChange:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCIceConnectionState","preciseIdentifier":"c:@E@RTCIceConnectionState"},{"kind":"text","text":")"}],"title":"peerConnection(_:didChange:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@client_sdk@objc(cs)Client(im)peerConnection:didChangeIceConnectionState:","modules":[{"name":"client_sdk"}],"navigatorTitle":[{"kind":"identifier","text":"peerConnection:didChangeIceConnectionState:"}]},"hierarchy":{"paths":[["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations"]]},"references":{"doc://com.ricoh.livestreaming/documentation/client_sdk/Client":{"role":"symbol","title":"Client","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Client"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Client"}],"url":"\/documentation\/client_sdk\/client"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didChange:)-1m295":{"role":"symbol","title":"peerConnection(_:didChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCIceConnectionState","preciseIdentifier":"c:@E@RTCIceConnectionState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-1m295","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didChangeIceConnectionState:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didchange:)-1m295"},"doc://com.ricoh.livestreaming/documentation/client_sdk":{"role":"collection","title":"client_sdk","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/RTCPeerConnectionDelegate-Implementations":{"role":"collectionGroup","title":"RTCPeerConnectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/client_sdk\/client\/rtcpeerconnectiondelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"peerConnection:didChangeIceConnectionState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didChangeIceConnectionState:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"peerConnection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peerConnection"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeIceConnectionState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCIceConnectionState","preciseIdentifier":"c:@E@RTCIceConnectionState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"newState"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/title","value":"Client"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/fragments","value":[{"kind":"identifier","text":"Client"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didChange:)-1m295\/title","value":"peerConnection:didChangeIceConnectionState:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didChange:)-1m295\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didChangeIceConnectionState:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}