{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionShouldNegotiate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"peerConnection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/client_sdk\/client\/peerconnectionshouldnegotiate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/client_sdk\/client\/peerconnectionshouldnegotiate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnectionShouldNegotiate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RTCPeerConnectionDelegate.peerConnectionShouldNegotiate(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"peerConnectionShouldNegotiate:"}],"role":"symbol","title":"peerConnectionShouldNegotiate(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionShouldNegotiate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@client_sdk@objc(cs)Client(im)peerConnectionShouldNegotiate:","extendedModule":"client_sdk","modules":[{"name":"client_sdk"}]},"hierarchy":{"paths":[["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations"]]},"references":{"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnectionShouldNegotiate(_:)":{"role":"symbol","title":"peerConnectionShouldNegotiate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionShouldNegotiate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnectionShouldNegotiate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnectionShouldNegotiate:"}],"url":"\/documentation\/client_sdk\/client\/peerconnectionshouldnegotiate(_:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk":{"role":"collection","title":"client_sdk","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/RTCPeerConnectionDelegate-Implementations":{"role":"collectionGroup","title":"RTCPeerConnectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/client_sdk\/client\/rtcpeerconnectiondelegate-implementations"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client":{"role":"symbol","title":"Client","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Client"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Client"}],"url":"\/documentation\/client_sdk\/client"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"peerConnectionShouldNegotiate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnectionShouldNegotiate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"peerConnectionShouldNegotiate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"peerConnection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnectionShouldNegotiate(_:)\/title","value":"peerConnectionShouldNegotiate:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnectionShouldNegotiate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnectionShouldNegotiate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/title","value":"Client"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/fragments","value":[{"kind":"identifier","text":"Client"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}