{"variants":[{"paths":["\/documentation\/client_sdk\/client\/rtcpeerconnectiondelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/client_sdk\/client\/rtcpeerconnectiondelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/RTCPeerConnectionDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didAdd:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didAdd:streams:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-1m295","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-467p5","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-6w35d","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didGenerate:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didOpen:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didRemove:)-65no3","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didRemove:)-9sd9r","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnectionShouldNegotiate(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"client_sdk"}],"role":"collectionGroup","title":"RTCPeerConnectionDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client"]]},"references":{"doc://com.ricoh.livestreaming/documentation/client_sdk/Client":{"role":"symbol","title":"Client","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Client"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Client"}],"url":"\/documentation\/client_sdk\/client"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didAdd:streams:)":{"role":"symbol","title":"peerConnection(_:didAdd:streams:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAdd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCRtpReceiver","preciseIdentifier":"c:objc(cs)RTCRtpReceiver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streams"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"RTCMediaStream","preciseIdentifier":"c:objc(cs)RTCMediaStream"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didAdd:streams:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didAddReceiver:streams:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didadd:streams:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didOpen:)":{"role":"symbol","title":"peerConnection(_:didOpen:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOpen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCDataChannel","preciseIdentifier":"c:objc(cs)RTCDataChannel"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didOpen:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didOpenDataChannel:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didopen:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk":{"role":"collection","title":"client_sdk","abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk","kind":"symbol","type":"topic","url":"\/documentation\/client_sdk"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didGenerate:)":{"role":"symbol","title":"peerConnection(_:didGenerate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didGenerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCIceCandidate","preciseIdentifier":"c:objc(cs)RTCIceCandidate"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didGenerate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didGenerateIceCandidate:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didgenerate:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didChange:)-6w35d":{"role":"symbol","title":"peerConnection(_:didChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCIceGatheringState","preciseIdentifier":"c:@E@RTCIceGatheringState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-6w35d","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didChangeIceGatheringState:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didchange:)-6w35d"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didAdd:)":{"role":"symbol","title":"peerConnection(_:didAdd:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAdd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCMediaStream","preciseIdentifier":"c:objc(cs)RTCMediaStream"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didAdd:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didAddStream:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didadd:)"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didRemove:)-9sd9r":{"role":"symbol","title":"peerConnection(_:didRemove:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRemove"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCMediaStream","preciseIdentifier":"c:objc(cs)RTCMediaStream"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didRemove:)-9sd9r","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didRemoveStream:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didremove:)-9sd9r"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didRemove:)-65no3":{"role":"symbol","title":"peerConnection(_:didRemove:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRemove"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"RTCIceCandidate","preciseIdentifier":"c:objc(cs)RTCIceCandidate"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didRemove:)-65no3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didRemoveIceCandidates:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didremove:)-65no3"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didChange:)-1m295":{"role":"symbol","title":"peerConnection(_:didChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCIceConnectionState","preciseIdentifier":"c:@E@RTCIceConnectionState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-1m295","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didChangeIceConnectionState:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didchange:)-1m295"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnection(_:didChange:)-467p5":{"role":"symbol","title":"peerConnection(_:didChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RTCSignalingState","preciseIdentifier":"c:@E@RTCSignalingState"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-467p5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnection:didChangeSignalingState:"}],"url":"\/documentation\/client_sdk\/client\/peerconnection(_:didchange:)-467p5"},"doc://com.ricoh.livestreaming/documentation/client_sdk/Client/peerConnectionShouldNegotiate(_:)":{"role":"symbol","title":"peerConnectionShouldNegotiate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"peerConnectionShouldNegotiate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RTCPeerConnection","preciseIdentifier":"c:objc(cs)RTCPeerConnection"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnectionShouldNegotiate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"peerConnectionShouldNegotiate:"}],"url":"\/documentation\/client_sdk\/client\/peerconnectionshouldnegotiate(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didAdd:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didAdd:streams:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-1m295","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-467p5","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didChange:)-6w35d","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didGenerate:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didOpen:)","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didRemove:)-65no3","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnection(_:didRemove:)-9sd9r","doc:\/\/com.ricoh.livestreaming\/documentation\/client_sdk\/Client\/peerConnectionShouldNegotiate(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/title","value":"Client"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client\/fragments","value":[{"kind":"identifier","text":"Client"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didAdd:streams:)\/title","value":"peerConnection:didAddReceiver:streams:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didAdd:streams:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didAddReceiver:streams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didOpen:)\/title","value":"peerConnection:didOpenDataChannel:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didOpen:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didOpenDataChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didGenerate:)\/title","value":"peerConnection:didGenerateIceCandidate:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didGenerate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didGenerateIceCandidate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didChange:)-6w35d\/title","value":"peerConnection:didChangeIceGatheringState:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didChange:)-6w35d\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didChangeIceGatheringState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didAdd:)\/title","value":"peerConnection:didAddStream:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didAdd:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didAddStream:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didRemove:)-9sd9r\/title","value":"peerConnection:didRemoveStream:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didRemove:)-9sd9r\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didRemoveStream:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didRemove:)-65no3\/title","value":"peerConnection:didRemoveIceCandidates:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didRemove:)-65no3\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didRemoveIceCandidates:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didChange:)-1m295\/title","value":"peerConnection:didChangeIceConnectionState:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didChange:)-1m295\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didChangeIceConnectionState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didChange:)-467p5\/title","value":"peerConnection:didChangeSignalingState:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnection(_:didChange:)-467p5\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnection:didChangeSignalingState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnectionShouldNegotiate(_:)\/title","value":"peerConnectionShouldNegotiate:"},{"op":"replace","path":"\/references\/doc:~1~1com.ricoh.livestreaming~1documentation~1client_sdk~1Client~1peerConnectionShouldNegotiate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"peerConnectionShouldNegotiate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}