# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_app
  pod 'CocoaLumberjack/Swift'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SwiftJWT'
  pod 'AnyCodable-FlightSchool', '~> 0.6.0'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            end
        end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
end
